apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-gke
  namespace: cert-manager
spec:
  acme:
    email: foo@example.com
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-manager-issuer-gke-account-key
    solvers:
    - selector:
        dnsZones:
          - foo.example.com
      dns01:
        cloudDNS:
          project: gcp-project-id
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json
